from enum import Enum


class MusicMood(Enum):
    AGGRESSIVE = "aggressive"
    CALM = "calm"
    CHILLED = "chilled"
    DARK = "dark"
    ENERGETIC = "energetic"
    EPIC = "epic"
    HAPPY = "happy"
    ROMANTIC = "romantic"
    SAD = "sad"
    SCARY = "scary"
    SEXY = "sexy"
    ETHEREAL = "ethereal"
    UPLIFTING = "uplifting"
    FEEL_GOOD = "feel_good"
    BOUNCY = "bouncy"
    DREAMY = "dreamy"
    MELANCHOLIC = "melancholic"
    MYSTERIOUS = "mysterious"
    PEACEFUL = "peaceful"
    INTENSE = "intense"
    PLAYFUL = "playful"
    NOSTALGIC = "nostalgic"
    TRIUMPHANT = "triumphant"